language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libboost-all-dev libgpm-dev libncurses5-dev liblog4cpp5-dev libnuma-dev libgeoip-dev libpcap-dev clang cmake
before_script:
  - wget http://sourceforge.net/projects/ntop/files/PF_RING/PF_RING-6.0.2.tar.gz/download
  - tar -xf PF_RING-6.0.2.tar.gz
  - sudo apt-get update
  - sudo apt-get install -y build-essential bison flex libnuma-dev wget tar make
  - cd userland/lib; ./configure --prefix=/opt/pf_ring; make; sudo make install
script: mkdir -p build; cd build; cmake ..; make
notifications:
  email:
    recipients:
      - pavel.odintsov@gmail.com
    on_success: change
    on_failure: always
