language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libboost-all-dev libgpm-dev libncurses5-dev liblog4cpp5-dev libnuma-dev libgeoip-dev libpcap-dev clang cmake
script: cmake
notifications:
  email:
    recipients:
      - pavel.odintsov@gmail.com
    on_success: change
    on_failure: always
